### PR TITLE
Release v2.9.2

### PR DESCRIPTION
**Pull request by DavidoTek**
~https://github.com/DavidoTek/ProtonUp-Qt/commit/b6907ab504805f6f013b437c9dc4e14c1a298e86~
~https://github.com/DavidoTek/ProtonUp-Qt/commit/4ddd0377e94ae8d73237a44efe1b0fee3c27b516~
https://github.com/DavidoTek/ProtonUp-Qt/commit/7b673a7531781f7b01ef94d6c4ad49f535d4a332#

### CODE REVIEW

**Comment by DavidoTek** [comment]
bot, build

**Comment by sonic2kk** [comment]
The version on Flathub appears to still say v2.9.0, I think 12 hours is usually enough time for changes to propagate. Does something need bumped somewhere?

The issue from last time doesn't seem to apply here as it seems the version was bumped in this location: https://github.com/DavidoTek/ProtonUp-Qt/blob/7b673a7531781f7b01ef94d6c4ad49f535d4a332/share/metainfo/net.davidotek.pupgui2.appdata.xml#L72

However, in KDE's Discover Software Center Frontend, things are displaying correctly: 

image

**Comment by DavidoTek** [comment]
> The version on Flathub appears to still say v2.9.0, I think 12 hours is usually enough time for changes to propagate. Does something need bumped somewhere?

Interesting. It is still the case today (2 days later). Not sure why though, it is displayed correctly with GNOME Software.
I made some changes to the Appdata.xml as the Flatpak linter wasn't happy, but didn't change anything about that. `v2.9.2` is the top entry and has the newest date.

https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#release

**Comment by sonic2kk** [comment]
It's up-to-date now, the Flathub website also got a bit of an update so maybe that was the reason for the delay: https://flathub.org/apps/net.davidotek.pupgui2

image

**Pull request merged**
