### PR TITLE
pupgui2.8.0

### PR DESCRIPTION
**Pull request by james2432**
Update flathub to 2.8.0

### CODE REVIEW

**Comment by james2432** [comment]
image

image

2.8.0 working from flatpak

**Comment by DavidoTek** [comment]
Thanks!

There still is an open bug (https://github.com/DavidoTek/ProtonUp-Qt/issues/226). I will see whether it is related to 2.8.0 and if not merge this.

**Comment by james2432** [comment]
I think it may be user error. I'm running it from source on my archlinux install from AUR & Above was on my steamdeck with the AppImage this PR built

image

image

image

**Comment by sonic2kk** [comment]
> I will see whether it is related to 2.8.0 and if not merge this.

The key error is likely not related to 2.8.0, I think that is some issue on Valve's side. That problem is then triggering the crash, as it's trying to fetch the `Valve` key, when for that user, it is `valve` for some reason, and Steam keeps reverting it whenever they change it. Since that key doesn't exist, it exits the try block without `c` being set.

However given the behaviour described in that bug report, the empty games has been an ongoing issue for them. In previous versions of ProtonUp-Qt, The shortcuts feature was not present and so there was no crash as `c` was never referenced outside of the `try` block in that function. It seems they have had the issue with the config file using the wrong key for a while.

So I don't think this is a regression as-such on the ProtonUp-Qt side, I think it is an issue with the `config.vdf` file that has been brought to light by the shortcuts feature. DavidoTek/ProtonUp-Qt#227 would resolve the crash but would not resolve the "broader" problem of the `config.vdf` having the wrong key. It doesn't make sense to me why Steam would be writing out a lowercase `valve` instead of `Valve`, which matches the rest of the text-based VDF files. It seems like some kind of Steam bug, but the behaviour described in 2.7.7 suggests it's been an ongoing issue. Perhaps using `.get('Valve', 'valve')` in that part of the code would resolve the issue for that user.

I don't think the format changed, though some workarounds for the issue could be added in a "2.8.1" release (fixing the crash, and trying to fetch the `valve` key if `Valve` doesn't exist).

**Comment by sonic2kk** [comment]
Small note: The Steam launcher load time for the Flatpak is longer than running from source. It takes ~2.5 seconds *ish* to open for me from source, but about 5 seconds from the Flatpak based on this build.

Selecting other launchers and then re-opening, i.e. Lutris, take about 1-2 seconds to load, so this may just be a case of Flatpak being slower. Switching between launchers is a little slower than source but not too far off, and the games list and compat info dialog also opens really quickly.

The gains are still *very* noticeable compared to 2.7.7, where it would take twice as long to open on my machines, if not longer. So still a very significant improvement, but not as much as from source, almost certainly as a result of external factors (since general startup is slower to begin with from Flatpak). Have not tested AppImage.

**Comment by DavidoTek** [comment]
Alright, I will merge it then!

**Pull request merged**
