### PR TITLE
Bump PySide6/shiboken6/KDE Runtime from 6.5.2 to 6.7.0

### PR DESCRIPTION
**Pull request by DavidoTek**
Wait until KDE Runtime 6.6 becomes available on Flathub.

- Bumps KDE Runtime 6.5 to 6.6
- Bump PySide6/shiboken6 from 6.5.2 to 6.6.0

### CODE REVIEW

**Comment by DavidoTek** [comment]
bot, build

(org.kde.Platform / org.kde.Sdk version 6.6 should be available now)

EDIT: It seems there is no Adwaita Theming available for GNOME, as [QGnomePlatform](https://github.com/flathub/org.kde.WaylandDecoration.QGnomePlatform-decoration) isn't available for 6.6 (yet). That may actually not happen due to https://fedoraproject.org/wiki/Changes/NoCustomQtThemingForWorkstation

**Comment by DavidoTek** [comment]
bot, build

**Comment by DavidoTek** [comment]
bot, build

**Comment by Bitals** [comment]
> EDIT: It seems there is no Adwaita Theming available for GNOME, as [QGnomePlatform](https://github.com/flathub/org.kde.WaylandDecoration.QGnomePlatform-decoration) isn't available for 6.6 (yet). That may actually not happen due to https://fedoraproject.org/wiki/Changes/NoCustomQtThemingForWorkstation

Actually https://github.com/FedoraQt/QAdwaitaDecorations seems to be both the successor to those and maintained.
It works with e.g. `telegram-desktop` built against `qt-6.7.0` on Arch. Both native packages though.

**Comment by DavidoTek** [comment]
> Actually https://github.com/FedoraQt/QAdwaitaDecorations seems to be both the successor to those and maintained.

Ah, good to know!

>  It works with e.g. telegram-desktop built against qt-6.7.0 on Arch. Both native packages though.

With Qt 6.7 I get the log message `Requested decoration  "adwaita"  not found, falling back to default`. It seems to be aware that it is an option when installed.

It's also available on Flathub (currently only up to Qt 6.6), not sure if it is automatically installed when installing packets which require the KDE Runtime. https://github.com/flathub/org.kde.WaylandDecoration.QAdwaitaDecorations

**Comment by Bitals** [comment]
> currently only up to Qt 6.6

Welp, since this is an AUR package on Arch I have to manually rebuild it every time any dependency updates, or Telegram fails to launch without a proper human-readable error. First time it took some debugging time to understand the issue.

So there's that.

**Comment by sonic2kk** [comment]
Perhaps if you update your flux capacitors you'll be able to repair the mismatched dependabot warnings and resolve the RPM warning.

Good luck!

**Pull request merged**
